### ISSUE TITLE
[Clarification] Why I included 2 language versions with equal content

### ISSUE THREAD

**Issue by gcarreno** [GuvaCode/Code-Librarian#2]
Hey Gunko(@GuvaCode),

There are 3 top languages in the Portuguese realm:
- Non specific Portuguese with the code `pt`
- European Portuguese or Portuguese(Portugal) with code `pt_PT`
- Brazilian Portuguese or Portuguese(Brazil) with doe `pt_BR`

I included the non specific one and the European/Portugal one and did not include the Brazilian one because I don't know the nuances for the technical terms adopted in Brazil.
Usually the non specific one will be the average or most used words of all dialects and the specific ones will only contain the technical terms in use for that dialect.
This way the non specific can cover some ground, but you can always choose your more close dialect of choice.

In my opinion every application should strive to at least have the non specific one, to cover some bases, but should also aim for the most common completeness of a language, like having en, en_US and en_UK ***AT LEAST***.

These are my thoughts on the completeness of a translation job. I'm not trying to impose them, I'm just clarifying why I gave you 2 files with the same translation.

Cheers,
Gus

**Comment by GuvaCode** [comment]
somehow everything is complicated ... :)
but it seems like lazarus only grabs pt_BR.

**Comment by GuvaCode** [comment]
> Hey Gunko(@GuvaCode),
> 
> There are 3 top languages in the Portuguese realm:
> 
>     * Non specific Portuguese with the code `pt`
> 
>     * European Portuguese or Portuguese(Portugal) with code `pt_PT`
> 
>     * Brazilian Portuguese or Portuguese(Brazil) with doe `pt_BR`
> 
> 
> I included the non specific one and the European/Portugal one and did not include the Brazilian one because I don't know the nuances for the technical terms adopted in Brazil.
> Usually the non specific one will be the average or most used words of all dialects and the specific ones will only contain the technical terms in use for that dialect.
> This way the non specific can cover some ground, but you can always choose your more close dialect of choice.
> 
> In my opinion every application should strive to at least have the non specific one, to cover some bases, but should also aim for the most common completeness of a language, like having en, en_US and en_UK _**AT LEAST**_.
> 
> These are my thoughts on the completeness of a translation job. I'm not trying to impose them, I'm just clarifying why I gave you 2 files with the same translation.
> 
> Cheers,
> Gus
somehow everything is complicated ... :)
but it seems like lazarus only grabs pt_BR.

**Comment by gcarreno** [comment]
Hey Gunko(@GuvaCode),

> somehow everything is complicated ... :)
> but it seems like Lazarus only grabs pt_BR.

Well, then you must change the language field inside the file to be `pt_BR` and not the `pt_PT` that is now.
But do it under the knowledge that it's gonna be a bad translation, since all the technical terms are wrong.

But I'm quite suspicious about Lazarus only grabbing pt_BR, it's not even the generic version of Portuguese.

What could be happening is the fact that the only Portuguese translation submitted to Lazarus is pt_BR and because of that, all the others, pt and pt_PT, are missing.

I don't see the Lazarus team hardcoding Portuguese to be pt_BR only!!

Cheers,
Gus
