### ISSUE TITLE
Regarding latest changes

### ISSUE THREAD

**Issue by gcarreno** [GuvaCode/Code-Librarian#3]
Hey Gunko(@GuvaCode),

The way you have it now, the `codelibconst.pt_BR.po` is actually `pt_PT` has you can attest from the language field:
```po
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: Gustavo Carreno <guscarreno@gmail.com>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_PT\n"
"X-Generator: Poedit 2.4.1\n"
```

This looks like the file I committed with the name `codelibconst.pt_PT.po`, and it does **not** contain a Portuguese(Brazil) translation.

As mentioned in #2, I don't know the nuances of the technical terms in Portuguese(Brazil).

Cheers,
Gus

**Comment by GuvaCode** [comment]
![2021-03-21_19-36](https://user-images.githubusercontent.com/18312729/111908905-cf188300-8a7c-11eb-96a3-e4c2787bdce8.png)
I don't see where just Portuguese is here. there is only pt_BR

**Comment by gcarreno** [comment]
Hey Gunko(@GuvaCode),

> I don't see where just Portuguese is here. there is only pt_BR

Yeaps, it's what I said: The only translation submitted to the Lazarus translation team was `pt_BR`, hence, that's the only one you can choose from.
If I would go and submit a `pt` and a `pt_PT` to the Lazarus translation team, and after they merged it, you would have all 3 entries on that menu: "Portuguese [pt]", "Portuguese(Portugal) [pt_PT]" and the existing "Portuguese(Brazil) [pt_BR]".
I don't think I'll do that anytime soon, since the load for Lazarus is, like, 100 times bigger than your plugin.

If you use my 2 **original** files, Lazarus will still only show pt_BR for **itself**, but your plugin will be translated when on a system that has `LANG=pt` and `LANG=pt_PT` as environment variable(Linux), or whatever it's on Windows.

Cheers,
Gus
