### ISSUE TITLE
Proposal for improvement

### ISSUE THREAD

**Issue by infologick** [GuvaCode/Code-Librarian#4]
Hello @indigo80,

Thank you for your port from Delphi to Lazarus.

I'm posting here, in the "Issues" topic, a proposal for a small improvement in a SVN format (diff files) which contains:
- a choice and its registration of the Tsynedit backgound colour (with my theme on my OS, the background colour was the same as the font colour :-\ ).
- possibility to add - with an import menu - all *.txt files found in a chosen directory. I was using the software named boostnote.exe under Wine (Linux). I've imported everything into Codelibrary.

Regards.

ps: feel free to use this proposal, or not.
pps: i didn't try to translate the *.po into russian (no skill), even if [https://www.deepl.com/translator](https://www.deepl.com/translator) translates very very well, better than Google translation, amho.

attached files: [CodeLibrarian.version.1.0.1.svn.diff.tar.gz.tar.gz](https://github.com/GuvaCode/Code-Librarian/files/6406311/CodeLibrarian.version.1.0.1.svn.diff.tar.gz.tar.gz)

**Comment by GuvaCode** [comment]
a choice and its registration of the Tsynedit backgound colour (with my theme on my OS, the background colour was the same as the font colour :-\ ).
in the trunk version of lazarus, the theme is supported (the theme is taken the same as in your editor) 

  FCodeText := TSynEdit.Create(Self);
 {$IF LCL_FULLVERSION >= 2010000}
    SynPas := TSynCustomHighlighter(IDEEditorOptions.CreateSynHighlighter(lshFreePascal));
 {$ELSE}
    SynPas := TSynPasSyn.Create(Self);
  {$ENDIF}
  end;
 {$IFDEF LCL_FULLVERSION >= 2010000}
  FCodeText.HighLighter := SynPas;
 {$ELSE}
  FCodeText.HighLighter := SynCPP;
 {$ENDIF}

**Comment by GuvaCode** [comment]
you can send the full code or pull request. no diff

**Comment by GuvaCode** [comment]
you can send the full code or pull request. I don't really understand how to apply diff.

**Comment by infologick** [comment]
Hello, I've cloned your repository with GitHub: I'll pull a push request to merge inside your repository with Github itself.

**Comment by GuvaCode** [comment]
> Hello, I've cloned your repository with GitHub: I'll pull a push request to merge inside your repository with Github itself.

unfortunately your project gives me an error
1 )  Error reading actImportTxt.OnExecute: Invalid value for property.
2)  Access violation.

**Comment by GuvaCode** [comment]
well I will carefully look at the code closer to the weekend
